version: '3.4'

services:
  react-app:
    container_name: react-app
    image: react-app
    build:
      context: .
      target: front-end
    env_file:
      - ./.env
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - rails-app

  rails-app:
    container_name: rails-app
    image: rails-app
    build:
      context: .
      target: backend
    env_file:
      - ./.env
    ports:
      - 3001:3000
    volumes:
      - ./:/app
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: